### ISSUE TITLE
Aff doesn't fail when running on Node

### ISSUE THREAD

**Issue by beckyconning** [slamdata/purescript-affjax#44]
The following program outputs `[Log] onerror@file:///Users/beckyconning/Documents/purescript-sketchpad/index.js:9693:24 (index.js, line 1302)` in a browser but is silent in Node. 

It appears print is never called.

```purescript
module Main where

import Prelude
import Debug.Trace

import Control.Monad.Aff
import Control.Monad.Eff.Console
import Data.Foreign
import Network.HTTP.Affjax

main = runAff print (print <<< show <<< _.status) $ (get "ajsdlfa" :: Affjax _ Foreign)
```

**Comment by stkb** [comment]
Have run into this issue too, and it's caused by the underlying [```xmlhttprequest```](https://github.com/driverdan/node-XMLHttpRequest) module, which to be blunt, doesn't work very well. It doesn't support things like the onerror event (the cause of this issue) and would just cause my program to hang in the case of a redirect. There are forks of ```xmlhttprequest``` that have fixed various things but with issues and PR's piling up, development on the module seems to have stopped. 

I went looking for a possible replacement and [```xhr2```](https://www.npmjs.com/package/xhr2) seems to be a good one. I tried using it in my app instead of ```xmlhttprequest``` (with a one-line change in ```Affjax.js```) and everything is working fine so far.

**Comment by paf31** [comment]
Perhaps `purescript-node-http` would be a good base for a Node HTTP client backend?

**Comment by stkb** [comment]
@paf31 Thanks for that; I'd also been looking for a PS library for a lightweight http server. Though for an http client, I like the Aff-style API that Affjax supplies, as well as being able to use the same API in both Node and the web browser.

**Comment by jdegoes** [comment]
PRs welcome! 😀 External dependencies should add minimal overhead to the library and be reflected in bower dependencies.

**Comment by stkb** [comment]
@jdegoes Thanks will submit a PR soon :) Am just checking everything works my end

**Comment by paf31** [comment]
Perhaps it would make sense to break a Node backend out into its own library, if dependencies are a concern. Creating an abstract backend should be straightforward enough, right? Something like `type Backend eff = forall req res. (Requestable req, Respondable res) => req -> Affjax eff res`.

**Comment by jdegoes** [comment]
I'm definitely open to feedback. I think a lot of people may run both node and browser tests in the same code base and want an `Ajax` library that does both; right now we sort of have node support in there but not for error cases.

**Comment by beckyconning** [comment]
Personally one of the biggest attractions I have to Javascript and PureScript is that DSLs / libraries / patterns can be shared between server and browser. I'd prefer to address this inside of Affjax rather than having different modules for dealing with HTTP requests depending on the environment.

**Comment by beckyconning** [comment]
But its the 'DSL' of Affjax that I think that would be valuable to share between the two rather than necessarily the implementation of it.
