### ISSUE TITLE
Travis tests not behaving as they should

### ISSUE THREAD

**Issue by garyb** [slamdata/purescript-affjax#48]
As discussed in this PR: https://github.com/slamdata/purescript-affjax/pull/47

Two problems:

1. The tests are failing, but not actually making travis fail.
2. They shouldn't be failing, but the test server is exiting immediately.

**Comment by stkb** [comment]
Just starting with point 2: the test server exiting immediately; I think it's referring to this line in the build before the test run?

```
The command "node ./test-server.js &" exited with 0.
```

However from reading [the Bash reference manual](https://www.gnu.org/software/bash/manual/bash.html#Lists), this seems to be completely normal and expected: 
> If a command is terminated by the control operator ‘&’, the shell executes the command asynchronously in a subshell. This is known as executing the command in the background. The shell does not wait for the command to finish, and the return status is 0 (true). 


As for all the errors in [the build log](https://travis-ci.org/slamdata/purescript-affjax/builds/84678217): ```Error: Expected a Right value```, they seem to have been caused by the test command not giving enough time for the test server to start up before running the tests. They're now gone in the build from PR #51 after I added a fix to that.

I'm not sure why the Travis builds were passing all this time with those errors, but immediately failed when I tried submitting #51; i guess it might have something to do with better error handling of ```xhr2``` compared to ```xmlhttprequest```.

With a commit based off that branch I tried "breaking" a test, and then [the build did fail correctly](https://travis-ci.org/stkb/purescript-affjax/builds/85758853). So I'm pretty sure that after merging #51 this issue will be resolved.
